### ISSUE TITLE
Stoned Chicken Feather Fix crash when using Ice And Fire ROTN

### ISSUE THREAD

**Issue by XvaleX10** [fonnymunkey/RLMixins#12]
[crash-2024-03-09_20.05.56-client.txt](https://github.com/fonnymunkey/RLMixins/files/14547471/crash-2024-03-09_20.05.56-client.txt)

**Comment by fonnymunkey** [comment]
As noted in the changelogs on CF, as of 1.3.0 all remaining Ice and Fire based tweaks in RLMixins are designed for use with the Copper and Lightning fork of Ice and Fire.
This is not an issue of Quark ROTN, rather that you are using Ice and Fire ROTN, which is coded differently than the Copper and Lightning fork and as such crashes.

As both the mods you are using are developed by ROTN, I recommend requesting them to just implement the fix directly, as I currently do not have plans to support multiple Ice and Fire versions at the same time.
