### ISSUE TITLE
`Slowed Item Entity Movement` making Thaumcraft's `Infernal Furnace` unable to work

### ISSUE THREAD

**Issue by Krutoy242** [fonnymunkey/RLMixins#16]
Setting this option to `true` making unable to use `Infernal Furnace` from mod Thaumcraft (and other furnaces from TC addons like `Thaumic Wonders` that working by the same princeple).
```ruby
        # Slows how often item entities update their position to improve performance
        B:"Slowed Item Entity Movement (Vanilla)"=false
```
How it should work: dropping items into furnace consume them and smelting:
![javaw_PFW1rg2EJJ](https://github.com/fonnymunkey/RLMixins/assets/936618/5fa52265-6f70-4891-b5b0-8622a1607908)

If `Slowed Item Entity Movement`  set to `true`, items just lie inside Furnace and cant be consumed.

[debug.log](https://github.com/user-attachments/files/15888594/debug.log)

**Comment by Krutoy242** [comment]
Thank you for the recommendation! It would save me lot of debugging time to find exact mod and config option that caused this bug if this caution would be written in config description 😅

**Comment by fonnymunkey** [comment]
I believe setting "Spawn Chunk Radius" to -1 has a possibility of interfering with some more complicated redstone mechanics but that may only be valid for older MC versions and wouldn't worry about it unless an issue presents.

"Entity Tracker Warning More Info" is a debug mixin I've already removed for the next version, I wouldn't recommend actually using it as you can technically view other players locations from a client with it.

Those and slowing items is all I can think of in your enabled list outside of enabling duplicate mixins across multiple mods, such as "Missing Particle Rendering" also being handled by RandomPatches.

**Comment by Krutoy242** [comment]
Thanks for advices.

**Comment by fonnymunkey** [comment]
Added a warning for next version in cfc1db7
