### ISSUE TITLE
`Smoothed Crouching` make player a rat

### ISSUE THREAD

**Issue by Krutoy242** [fonnymunkey/RLMixins#17]
After enable option `Smoothed Crouching (Vanilla)` my player is becomes knee-level of sight, and cursor not looking of actual block player looks.

![javaw_cClQL8SBIM](https://github.com/user-attachments/assets/3364305b-fb60-45fd-be7a-f22d2d84bf66)

Log: https://mclo.gs/C7ZnKPd

**Comment by Krutoy242** [comment]
This is [Enigmatica 2: Expert - Extended](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack. To reproduce issue you need to disable [this two options](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/randompatches.cfg#L79-L83) and enable one in RLMixins config.

**Comment by fonnymunkey** [comment]
Figured it out, the conflicting mod is Aqua Acrobatics.
RLMixins, RandomPatches, and Aqua Acrobatics all implement the same "Smooth Crouch" tweak.

RLMixins and RandomPatches both let you enable/disable the tweak, however Aqua Acrobatics only disables its tweak if RandomPatches is installed.

As such, handling of the "Smooth Crouch" tweak should be deferred to Random Patches and Aqua Acrobatics if installed;
RLMixins and RandomPatches -> Use whichever tweak
RLMixins and Aqua Acrobatics -> Use Aqua Acrobatics tweak
RandomPatches and Aqua Acrobatics -> Use RandomPatches tweak
All three -> Use RandomPatches tweak

I believe all 3 tweaks functions essentially the same in terms of in game appearance.

As it is a duplicated tweak and not two different tweaks conflicting, I have no real plans to "fix" this, however I do plan with the next overhaul version to add logging for known conflicting mod options to warn about situations such as this.
