### ISSUE TITLE
Spongeforge Compatibility?

### ISSUE THREAD

**Issue by Serimah** [fonnymunkey/RLMixins#2]
Hey there, would it be possible to get RLMixins to work with Spongeforge?
(Yes, I am aware people are not overly fond of Sponge but as a Server Owner this is pretty crucial)
I would appreciate if you could have a look at it. Thank you in Advance!

[console log.txt](https://github.com/fonnymunkey/RLMixins/files/10487652/console.log.txt)

**Comment by fonnymunkey** [comment]
All Mixins can be toggled off in the config, for that error turn off "Entity Tracker Desync (Vanilla)".
Its a non-critical patch to a vanilla/forge issue and I would not be surprised if Sponge/SpongeForge already has it implemented themselves.

**Comment by Serimah** [comment]
Thank you so much for your response, I wasn't even aware of the indepth Options available by RLMixins.
In the end I had to turn off the following for it to start with Spongeforge:
Outdated Chunk Data (Vanilla)
Offhand Enchants (Vanilla/RLCombat)
Entity Tracker Desync (Vanilla)
(Written down incase anyone else will struggle with this)

So, thanks again!

**Comment by fonnymunkey** [comment]
Do you have the error log for the Offhand Enchants crash? The other two are just vanilla/forge patches that aren't critical for RLCraft but the Offhand Enchants one is slightly more important.

**Comment by Serimah** [comment]
Oh sure, here you go. 
[log.txt](https://github.com/fonnymunkey/RLMixins/files/10493904/log.txt)

**Comment by fonnymunkey** [comment]
Latest version in test 5 when it releases should fix the issue with the Offhand Enchants mixin, and it should be fine to reenable.

Ironically, Sponge's changes that were conflicting with my changes functionally do nothing on SpongeForge, because Forge already implements the exact same changes.
