### ISSUE TITLE
Epic Siege Crash in heavily modded environment.

### ISSUE THREAD

**Issue by Foreck1** [fonnymunkey/RLMixins#31]
https://paste.ee/p/GoQun

With the latest version of ESM released, EpicSiegeMod-13.169, the `Digging AI (Epic Siege Mod)` patch from RLMixins causes a crash due to a class file not found.

**Comment by fonnymunkey** [comment]
The EpicSiegeMod patches in RLMixins are IIRC based on 13.167 (13.168 may work as well as that was only a small change), which is the latest non-beta release.
13.169 was refactored compared to 13.167 and as such the RLMixin patches for 13.167 won't work on 13.169.
When we tested the newer beta release (13.169) we found numerous new bugs with it such as the configs not working and resetting whenever modified, and didn't really find benefits from using the newer version compared to sticking with the older version and modifying that.
(I did attempt to reach out to the author about maintaining the 1.12.2 version to do a proper rewrite but did not receive a response.)

**Comment by Foreck1** [comment]
That is understandable. In our personal use, there have been as many bugs with one version as with the other, but the beta did work well enough to the point where the individual configuration allowed for greated control.
If the mixin is only intended for the release version, then this issue is redundant.
