### ISSUE TITLE
Enable Better Dragon Bites (IceAndFire) crashes game during startup

### ISSUE THREAD

**Issue by KnightCa** [fonnymunkey/RLMixins#7]
Minecraft 1.12.2
Forge 14.23.5.2860
RLMixins 1.2.15
Ice and Fire 1.9.1

        # Makes dragons bite the player for the same amount as they bite other mobs, and heal on bites
        B:"Enable Better Dragon Bites (IceAndFire)"=true

The crash happens during client startup. All of the other options with Ice and Fire work. I'd love to get a way to get dragons to do this.

Error Message: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/entity/EntityDragonBase
[crash-2023-08-06_01.06.35-client.txt](https://github.com/fonnymunkey/RLMixins/files/12268933/crash-2023-08-06_01.06.35-client.txt)

**Comment by KnightCa** [comment]
I spoke to soon. Also had a issue with the following setting:

        # Fix issues with Dragon Skull, Dragon Egg, Dragon Horn, and Myrmex Egg deleting items or duping when used in offhand
        B:"InF Offhand Items (IceAndFire)"=false

Error Message: The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/item/ItemDragonHornActive
[crash-2023-08-06_02.31.56-client.txt](https://github.com/fonnymunkey/RLMixins/files/12269093/crash-2023-08-06_02.31.56-client.txt)

**Comment by fonnymunkey** [comment]
RLMixins is primarily built for RLCraft, which uses InF 1.7.1, so while some of the InF-related patches will still work with new versions, not all of them will, like those.
I do not have plans of attempting to support both versions at the same time, especially as it will likely be changing to a fork instead with even more breaking changes soon.

**Comment by KnightCa** [comment]
I hadn't realized that InF was a mod (I thought it just was shorthand for
Ice and Fire). Can you update the config to show those settings are for
that mod? Thanks so much for your amazing work.

**Comment by KnightCa** [comment]
Oops, I just now caught on. You mean that RLMixin is designed to work with
Ice and Fire version 1.7.1, which is what RLCraft uses. Now I follow.
