### ISSUE TITLE
 SME overhaul mixin doesn't recognize adept enchantments in SME

### ISSUE THREAD

**Issue by nimuck** [fonnymunkey/RLMixins#8]
I loaded minecraft with the minimum settings required for the 'SME overhaul' mixin but an unexpected crash occurred.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Rin's So Many Enchantments? (somanyenchantments)
Caused by: java.lang.NoClassDefFoundError: com/Shultrea/Rin/Ench0_4_0/EnchantmentAdept
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Absolutely no idea why I'm getting NoClassDefFoundError even though SME is installed properly.

Only SME-related options were turned on.
are there any unspecified dependencies in the option?
[crash-2023-09-11_17.43.30-client.txt](https://github.com/fonnymunkey/RLMixins/files/12578353/crash-2023-09-11_17.43.30-client.txt)

**Comment by fonnymunkey** [comment]
That class annoying imported Charm's EnchantmentHelper instead of Vanilla's EnchantmentHelper, it will be fixed in the next update.
