### ISSUE TITLE
Disable custom spawn checks for SRP breaks spawning entirely

### ISSUE THREAD

**Issue by metaface** [fonnymunkey/RLMixins#9]
If you have this option enabled they won't spawn naturally at all, we've been wondering why it has been 30 in-game days and not a single buglin has spawned yet. Took me a lot of looking around to notice this setting and realize it might be causing the issue, disabled it, reloaded the game, everything started working again.

**Comment by fonnymunkey** [comment]
If you are using evolution phases (their custom spawning system) and disable custom spawning, yes, spawning will be disabled.
If you have evolution phases and their other custom spawning options disabled, mobs will still spawn with generic vanilla spawning and spawners.
